source 'https://github.com/CocoaPods/Specs.git'

target 'JFELocationManager', :exclusive => true do
  pod "JFELocationManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JFELocationManager", :path => "../"

  
end
